
package eu.openmos.agentcloud.ws.agentplatformkiller.wsimport;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgentPlatformKiller", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", wsdlLocation = "/wsdl/wsAgentPlatformKiller.wsdl")
public class AgentPlatformKiller_Service
    extends Service
{

    private final static URL AGENTPLATFORMKILLER_WSDL_LOCATION;
    private final static WebServiceException AGENTPLATFORMKILLER_EXCEPTION;
    private final static QName AGENTPLATFORMKILLER_QNAME = new QName("http://cloudinterface.agentcloud.openmos.eu/", "AgentPlatformKiller");

    static {
        AGENTPLATFORMKILLER_WSDL_LOCATION = eu.openmos.agentcloud.ws.agentplatformkiller.wsimport.AgentPlatformKiller_Service.class.getResource("/wsdl/wsAgentPlatformKiller.wsdl");
        WebServiceException e = null;
        if (AGENTPLATFORMKILLER_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/wsAgentPlatformKiller.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        AGENTPLATFORMKILLER_EXCEPTION = e;
    }

    public AgentPlatformKiller_Service() {
        super(__getWsdlLocation(), AGENTPLATFORMKILLER_QNAME);
    }

    public AgentPlatformKiller_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGENTPLATFORMKILLER_QNAME, features);
    }

    public AgentPlatformKiller_Service(URL wsdlLocation) {
        super(wsdlLocation, AGENTPLATFORMKILLER_QNAME);
    }

    public AgentPlatformKiller_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGENTPLATFORMKILLER_QNAME, features);
    }

    public AgentPlatformKiller_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgentPlatformKiller_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgentPlatformKiller
     */
    @WebEndpoint(name = "AgentPlatformKillerImplPort")
    public AgentPlatformKiller getAgentPlatformKillerImplPort() {
        return super.getPort(new QName("http://cloudinterface.agentcloud.openmos.eu/", "AgentPlatformKillerImplPort"), AgentPlatformKiller.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgentPlatformKiller
     */
    @WebEndpoint(name = "AgentPlatformKillerImplPort")
    public AgentPlatformKiller getAgentPlatformKillerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cloudinterface.agentcloud.openmos.eu/", "AgentPlatformKillerImplPort"), AgentPlatformKiller.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGENTPLATFORMKILLER_EXCEPTION!= null) {
            throw AGENTPLATFORMKILLER_EXCEPTION;
        }
        return AGENTPLATFORMKILLER_WSDL_LOCATION;
    }

}
