
package eu.openmos.agentcloud.ws.agentplatformkiller.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgentPlatformKiller", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgentPlatformKiller {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "shutdownStatus", targetNamespace = "")
    @RequestWrapper(localName = "shutdown", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.agentplatformkiller.wsimport.Shutdown")
    @ResponseWrapper(localName = "shutdownResponse", targetNamespace = "http://cloudinterface.agentcloud.openmos.eu/", className = "eu.openmos.agentcloud.ws.agentplatformkiller.wsimport.ShutdownResponse")
    public int shutdown();

}
